[package]
name = "remove-n-list"
version = "0.1.0"
authors = ["Guangzhi Xu <xuguangzhi@kingsoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
